### ISSUE TITLE
运行到这就没反应了

### ISSUE THREAD

**Issue by Funfun404** [EnkanSakura/auto-cpdaily#2]
![QQ图片20200428192726](https://user-images.githubusercontent.com/64473166/80482202-5b621900-8986-11ea-9f9f-873706934ff5.jpg)

**Comment by Funfun404** [comment]
我想的是是不是  Do(CURRENT_DATE+"学生日报信息"); 这句要改 ，
就试了下面几句
`Do("【重要收集】宁波大学本科生每日健康打卡-晚报（"+CURRENT_DATE+"）");
Do("【重要收集】宁波大学本科生每日健康打卡-晚报（4月28）");`
依然不行

**Comment by EnkanSakura** [comment]
啊这，我们学校“重要收集”下面那一条消息是“x月x日学生日报信息收集”
我没考虑到其他学校的信息可能不一样
我改一下检测的方法，一会提交

**Comment by Funfun404** [comment]
好滴，感谢

**Comment by EnkanSakura** [comment]
没想到你们学校一天填两次，真是受苦

**Comment by Funfun404** [comment]
呜呜呜早上那次已经连续两天错过了，于是愤而查脚本

**Comment by EnkanSakura** [comment]
你尝试一下把
```
Do(CURRENT_DATE+"学生日报信息");
```
改成
```
Do("未填写 >");
```
然后运行试一试

**Comment by Funfun404** [comment]
可以了！感谢！

**Comment by EnkanSakura** [comment]
好的，我提交commit
