### ISSUE TITLE
关于锁屏解锁

### ISSUE THREAD

**Issue by Funfun404** [EnkanSakura/auto-cpdaily#3]
我观察了一下，系统是先左滑然后再输入密码的，
我的是小米系统，是上滑输入密码
但是我没找到代码里哪句是控制这个动作的，能注释一下咩
（dbq 又双叒叕是我）

**Comment by EnkanSakura** [comment]
Unlock函数的第一句gesture函数，用于模拟手势操作
详细可查阅文档[gesture条目](https://hyb1996.github.io/AutoJs-Docs/#/coordinatesBasedAutomation?id=gestureduration-x1-y1-x2-y2-)
因为我的手机锁屏界面无论往哪个方向滑动都可以解锁，我就写了从左向右滑的手势
一会我把八个方向的滑动都写上XD

**Comment by Funfun404** [comment]
诶，那么是不是理论上可以用这个函数来解手势的那个锁屏

**Comment by EnkanSakura** [comment]
确实可以，但是不同手机屏幕分辨率不一样，不同系统⑨个点的相对位置也可能不一样
我的手机绘制图案的控件是一个正方形区域，分成九等分后每个点差不多都在各个正方形中心，姑且很方便算出来各个点的坐标，但这个控件跟其他的控件相比没有特殊的属性，换成其他系统是什么情况我也不知道
所有就先搁着了，反正不是太重要的功能╮(╯▽╰)╭

**Comment by Funfun404** [comment]
哈哈哈猴，我自己研究下试试看
还有我的手机在上滑的时候设置的（200，1920），（200，500）是解不开的
要尽量设置长一点
