### ISSUE TITLE
填报信息更新了

### ISSUE THREAD

**Issue by www338** [EnkanSakura/auto-cpdaily#4]
大大看一下填报信息更换了怎么搞呀

**Comment by EnkanSakura** [comment]
提供一下截图

**Comment by www338** [comment]
![image](https://user-images.githubusercontent.com/59461656/82021852-32e45980-96be-11ea-8a8a-92e3ba40a0af.png)

**Comment by EnkanSakura** [comment]
已更新（前几天pull后忘记回复）
