### ISSUE TITLE
不能完整运行

### ISSUE THREAD

**Issue by YYplus** [EnkanSakura/auto-cpdaily#5]
填完地址后，就没反映了，
![Screenshot_20200524-113947__01](https://user-images.githubusercontent.com/65841378/82745569-95bdab00-9db8-11ea-9cf9-b45235ab9914.jpg)
我应该改哪？谢谢

**Comment by EnkanSakura** [comment]
啊你的表跟我的完全不一样，你先看看autojs文档里基于控件的操作那部分尝试着改一下，测试的时候记得把自动提交的那几行代码注释掉

**Comment by YYplus** [comment]
相同的文本在屏幕中出现多次这个UiSelector.textContains(str)咋能指定点击第几个文本

**Comment by EnkanSakura** [comment]
定义一个变量，用textContains(str).find()将其初始化，.find()函数返回界面中所有符合条件的控件的集合，然后用循环语句对控件集合中每一个元素进行click()操作。但有的控件的text和selector是分离的，需要通过父子关系得到兄弟控件再进行操作，控件之间的关系可以用sdktool里的uiautomatorviewer查看

**Comment by YYplus** [comment]
做为完全不懂编程的人，我完全看不懂你说。。我用你原有的代码看了文档，搞定了填大部分，现在setText([1, ]“36.1”)；这个报错，还有就是两个一样的文本点两次取消的问题了，它并没有跳转到下一条，你能帮帮我吗

**Comment by EnkanSakura** [comment]
原来没有学过编程啊，那已经很厉害了。“今日体温”那个文本框里面默认的内容是什么

**Comment by YYplus** [comment]
没有默认内容，需要自己填，setText(“36.1”)这样的话可以填，但会填到所有框里

**Comment by EnkanSakura** [comment]
计算机程序的序号是从0开始的，日常说的第1个在程序里应为第0个，改成下面这样就行了
`setText([0]"36.1");`

**Comment by YYplus** [comment]
好的，谢谢

**Comment by EnkanSakura** [comment]
写错了，应该是这样`setText(0,"36.1");`

**Comment by EnkanSakura** [comment]
选项改成这样应该就行了
```javascript
var bottom = textContains("无").find();
for(var i = 0; i < b_end; i++)
{
    bottom[i].parent().child(1).click();
}
bottom = textContains("未").find();
for(var i = 0; i < b_end; i++)
{
    bottom[i].parent().child(1).click();
}
```

**Comment by YYplus** [comment]
![ZF7%%7@RVP@F 7~HOWUWA}N](https://user-images.githubusercontent.com/65841378/82775887-a08d4400-9e7b-11ea-9b5e-6cbfd1d9d2e5.png)
这样对了吗？
谢谢

**Comment by EnkanSakura** [comment]
你把最后三行注释掉运行一遍看看有没有问题，没问题把注释取消就行
```
//Do(xxx);
//sleep(xxx);
//Do(xxx);
```

**Comment by YYplus** [comment]
嗯，今天我已经手动提交了，只能等明天试了

**Comment by YYplus** [comment]
问题全部搞定，谢谢

**Comment by YYplus** [comment]
所有都填好了，但报了个错
08:18:15.701/E: TypeError: Cannot call method "parent" of undefined (<[remote]cpdaily>#119)	at script.Fill(<[remote]cpdaily>:119)	at script(<[remote]cpdaily>:156)

**Comment by YYplus** [comment]
setText(0,"36.1");
    var bottom = textContains("无").find();
    var b_end = bottom.size() - 1;
    for(var i = 0; i < b_end; i++)
    {
        bottom[i].parent().child(1).click();
    }
    bottom = textContains("未").find();
    for(var i = 0; i < b_end; i++)
{
    bottom[i].parent().child(1).click();
}
    if(HAVE_CODE)
    {
        bottom[b_end].parent().parent().child(0).child(1).click();
        while(!textContains(CODE_COLOR).findOne().parent().child(1).click());
    }
    else
    {
        bottom[b_end].parent().parent().child(0).child(0).click();
        while(!textContains("未申请").findOne().parent().child(1).click());
    }
    // Do("提交给辅导员");
    // sleep(1000);
    // Do("提交");
}

//脚本执行部分
auto.waitFor();     //等待辅助功能开启
setScreenMetrics(1080, 1920);

while(!device.isScreenOn())
{
    device.wakeUp();
    sleep(1000);
}
sleep(1000);
if(packageName("com.android.systemui").findOne(300))
{
    Unlock();   //唤醒屏幕，解锁
}

toast("即将启动今日校园");  //启动APP
sleep(2000);
launch("com.wisedu.cpdaily");
sleep(5000);

Fill();     //填表

**Comment by EnkanSakura** [comment]
删去
```
if(HAVE_CODE)
{
bottom[b_end].parent().parent().child(0).child(1).click();
while(!textContains(CODE_COLOR).findOne().parent().child(1).click());
}
else
{
bottom[b_end].parent().parent().child(0).child(0).click();
while(!textContains("未申请").findOne().parent().child(1).click());
}
```

**Comment by YYplus** [comment]
还是报，报错的是119行
119 bottom [i] .parent（）。child（1）.click（）;
}
if（HAVE_CODE）
{
bottom [b_end] .parent（）。parent（）。child（0）.child（1）.click（）;
while（！textContains（CODE_COLOR）.findOne（）。parent（）。child（1）.click（））;
}
else
{
bottom [b_end] .parent（）。parent（）。child（0）.child（0）.click（）;
while（！textContains（“未申请”）.findOne（）。parent（）。child（1）.click（））;
}
// Do（“提交给辅导员”）;
// sleep（1000）;
// Do（“提交”）;

**Comment by EnkanSakura** [comment]
把两个`for(var i = 0; i < b_end; i++)`里的`b_end`改成`bottom.size()`，`var b_end = bottom.size() - 1;`那行删掉

**Comment by YYplus** [comment]
改完以后不报错了但最后勾选确认以认真查看，且填写信息无误不能勾选了，于是我在后面加了
while(!textContains("确认").findOne().parent().child(1).click());
这个，现在欧克了，不知道对不对

**Comment by EnkanSakura** [comment]
运行没问题就是对的

**Comment by YYplus** [comment]
ok,谢谢，可以关问题了
